templates:
    discord.txt: '%userprofile%\AppData\Roaming\BetterDiscord\themes\pywal-discord-default.theme.css'
    obsidian.txt: '%userprofile%\Documents\Notes\.obsidian\themes\pywal.css'
wsl: ''
light_mode: false