templates:
    discord: '%userprofile%\AppData\Roaming\BetterDiscord\themes\pywal-discord-default.theme.css'
    obsidian: '%userprofile%\Documents\Notes\.obsidian\themes\pywal.css'
    test: 'D:\Desktop\test.txt'
wsl: ''
light_mode: false